name: Test CI (No Publish)

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      test_type:
        description: 'Test type to run'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - dry-run
          - full-test

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Test npm publish (dry-run)
      run: npm publish --dry-run

    - name: Check what would be published
      run: |
        echo "Files that would be published:"
        npm pack --dry-run 2>&1 | grep -E "npm notice" || true

    - name: Version check
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "Package version: $PACKAGE_VERSION"

        # Check if version exists on npm
        if npm view noodle-perplexity-mcp@$PACKAGE_VERSION version 2>/dev/null; then
          echo "⚠️ Version $PACKAGE_VERSION already exists on npm"
        else
          echo "✅ Version $PACKAGE_VERSION is new and would be published"
        fi